### ISSUE TITLE
fix the preview process to be blatant fast

### ISSUE THREAD

**Issue by zalsaeed** [zalsaeed/cgav#21]
Regardless of the speed of generating the certificate, the preview must be very fast. Generating images instead of PDFs could be a solution.

**Comment by ralhazmi** [comment]
**What should we do to complete this task?** 
In this task I use Pillow Library to generate Image for preview , draw the template inside it , write the certificate content with specific x,y positions ,colors and font on it.

Addressing the following subtasks will ensure successful completion of the task:

- [ ] Creating a image instead of the actual certificate.
- [ ] Standardizing the dimensions of the image.
- [ ] Standardizing the font sizes.
- [ ] Take customization from the input fields and reflecting them on the preview image.
- [ ] Reflecting position adjustments on the image onto the actual certificate PDF.

**Comment by ralhazmi** [comment]
The library used was changed from Pillow to matplotlib so that the format of the certificate in preview matches the actual certificate generated and to preserve the properties and features of the file as PDF, as the matplotlib library has proven its effectiveness in this task.
